config/routes.rb
Rails.application.routes.draw do
  root to: "tops#index"
  resources :housings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/housing.rb
class Housing < ApplicationRecord
  has_many :near_stations, inverse_of: :housing
  accepts_nested_attributes_for :near_stations, reject_if: :all_blank
  validates :build, presence: true
end

app/models/near_station.rb
class NearStation < ApplicationRecord
  belongs_to :housing, inverse_of: :near_stations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/housings_controller.rb
class HousingsController < ApplicationController
  before_action :set_housing, only: [:show, :edit, :update, :destroy]

  def index
    @housings = Housing.all
  end

  def new
    @housing = Housing.new
    2.times { @housing.near_stations.build }
  end

  def create
    @housing = Housing.new(params_housing)
    if params[:back]
      render 'new'
    else
      if @housing.save
        redirect_to housing_path(@housing.id)
      else
        render 'new'
      end
    end
  end

  def show
  end

  def edit
    @housing.near_stations.new
  end

  def update
    if @housing.update(params_housing)
      redirect_to housings_path, notice:"変更しました！"
    else
      render :edit
    end
  end

  def destroy
    @housing.destroy
    redirect_to housings_path, notice:"削除しました！"
  end

  private

  def set_housing
    @housing = Housing.find(params[:id])
  end

  def params_housing
    params.require(:housing).permit(
      :build,
      :rent,
      :add,
      :year,
      :remarks,
      near_stations_attributes:[
        :id,
        :line,
        :station,
        :walk])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/housings_helper.rb
module HousingsHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}円"
  end
end

app/views/housings/_form.html.erb
<%= form_for @housing do |f| %>
  <table>
    <tr><td><%= f.label :"物件名" %></td></tr>
    <tr><td><%= f.text_field :build %></td></tr>
    <tr><td><%= f.label :"賃料" %></td></tr>
    <tr><td><%= f.text_field :rent %>円</td></tr>
    <tr><td><%= f.label :"住所" %></td></tr>
    <tr><td><%= f.text_field :add %></td></tr>
    <tr><td><%= f.label :"築年数" %></td></tr>
    <tr><td><%= f.text_field :year %>年</td></tr>
    <tr><td><%= f.label :"備考" %></td></tr>
    <tr><td><%= f.text_area :remarks %></td></tr>
  </table>
    <div class="borderLine"></div>
  <table>
    <% count = 1 %>
    <%= f.fields_for :near_stations do |a| %>
      <tr><td><h3>最寄駅<%= count %></h3></td></tr>
      <tr><td><%= a.label :"路線名" %></td></tr>
      <tr><td><%= a.text_field :line %></td></tr>
      <tr><td><%= a.label :"駅名" %></td></tr>
      <tr><td><%= a.text_field :station %></td></tr>
      <tr><td><%= a.label :"徒歩分数" %>分</td></tr>
      <tr><td><%= a.text_field :walk %></td></tr>
    <% count += 1 %>
    <% end %>
    <tr><td><%= f.submit :"登録する" %></td></tr>
  </table>
<% end %>

app/views/housings/edit.html.erb
<h1>編集</h1>
<h2>物件編集</h2>
<%= render 'form', housing: @housing %>

<%= link_to '戻る', :back %>

app/views/housings/index.html.erb
<h1>一覧</h1>
<div class="borderLine"></div>
<h2>物件一覧</h2>
<table>
  <tr>
    <th>物件名</th>
    <th>賃料</th>
    <th>住所</th>
    <th>築年数</th>
    <th>備考</th>
  </tr>
<% @housings.each do |h| %>
  <tr>
    <td><%= h.build %></td>
    <td><%= h.rent.to_s(:delimited, delimiter: ',') %>円</td>
    <td><%= h.add %></td>
    <td><%= h.year %>年</td>
    <td><%= h.remarks %></td>
    <td><%= link_to '詳細', housing_path(h.id) %></td>
    <td><%= link_to '編集', edit_housing_path(h.id) %></td>
    <td><%= link_to '削除', housing_path(h.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>
<%= link_to '物件を登録する', new_housing_path %>

app/views/housings/new.html.erb
<h1>登録</h1>
<h2>物件登録</h2>
<%= render 'form', housing: @housing %>

<%= link_to '戻る', housings_path %>

app/views/housings/show.html.erb
<h1>閲覧</h1>
<p>物件名：<%= @housing.build %></p>
<p>賃料：<%= converting_to_jpy(@housing.rent) %></p>
<p>住所：<%= @housing.add %></p>
<p>築年数：<%= @housing.year %>年</p>
<p>備考：<%= @housing.remarks %></p>
<div class="borderLine"></div>
<% count = 1 %>
<% @housing.near_stations.each do |near| %>
  <h3>最寄駅<%= count %></h3>
  <p>路線名：<%= near.line %></p>
  <p>駅名：<%= near.station %></p>
  <p>徒歩分数：<%= near.walk %>分</p>
  <% count += 1 %>
<% end %>
<%= link_to '編集', edit_housing_path(@housing.id) %>｜<%= link_to '戻る', housings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevExam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>